admins: [1919745140] 

forwards:
  - source: -1001728410290
    dest: [-1001761089302,-1001713025945]

plugins:
   replace:
    text:
      "RUN BANAKAR OUT": Run Banakar Out
      "CATCH OUTâœ”ï¸âœ”ï¸": ğŸš¾ CATCH OUT ğŸš¾
      "WIDE âœ”ï¸âœ”ï¸" : ğŸ¾ WIDE ğŸ¾
      "RUN OUTâœ”ï¸âœ”ï¸": ğŸš¾ RUN OUT ğŸš¾
      "âœ”ï¸âœ”ï¸": " "
